# Generated by Django 4.0.1 on 2022-11-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePunto', models.CharField(max_length=100, verbose_name='Nombre punto de reciclaje')),
                ('direccionPunto', models.CharField(max_length=250, verbose_name='Dirección punto de reciclaje')),
                ('descripcionPunto', models.TextField(verbose_name='Descripción punto de reciclaje')),
                ('lngLat', models.CharField(max_length=700, verbose_name='Latitud y Longitud ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(verbose_name='Puntaje de valoración')),
                ('comentarios', models.TextField(verbose_name='Comentario')),
                ('idPunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.puntos')),
            ],
        ),
    ]
